//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.13 at 08:30:49 PM IST 
//


package com.naren.openstack.dataobjects.rest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns="http://www.w3.org/1999/xhtml" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:csapi="http://docs.openstack.org/compute/api/v1.1" xmlns:jcapi="http://www.jc.jcstack/compute" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsdxt="http://docs.rackspacecloud.com/xsd-ext/v1.0"&gt;
 * 					An network-accessible address, usually described by URL, where a service may
 * 					be accessed. If using an extension for templates, you can create an endpoint
 * 					template, which represents the templates of all the consumable services that
 * 					are available across the regions.
 * 				&lt;/p&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for Endpoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Endpoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="versionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tenantId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="region" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="publicURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="internalURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="adminURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="versionInfo" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="versionList" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Endpoint")
public class Endpoint {

    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "versionId")
    protected String versionId;
    @XmlAttribute(name = "tenantId", required = true)
    protected String tenantId;
    @XmlAttribute(name = "region", required = true)
    protected String region;
    @XmlAttribute(name = "publicURL")
    @XmlSchemaType(name = "anyURI")
    protected String publicURL;
    @XmlAttribute(name = "internalURL")
    @XmlSchemaType(name = "anyURI")
    protected String internalURL;
    @XmlAttribute(name = "adminURL")
    @XmlSchemaType(name = "anyURI")
    protected String adminURL;
    @XmlAttribute(name = "versionInfo")
    @XmlSchemaType(name = "anyURI")
    protected String versionInfo;
    @XmlAttribute(name = "versionList")
    @XmlSchemaType(name = "anyURI")
    protected String versionList;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the versionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * Sets the value of the versionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionId(String value) {
        this.versionId = value;
    }

    /**
     * Gets the value of the tenantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * Sets the value of the tenantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantId(String value) {
        this.tenantId = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the publicURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicURL() {
        return publicURL;
    }

    /**
     * Sets the value of the publicURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicURL(String value) {
        this.publicURL = value;
    }

    /**
     * Gets the value of the internalURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalURL() {
        return internalURL;
    }

    /**
     * Sets the value of the internalURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalURL(String value) {
        this.internalURL = value;
    }

    /**
     * Gets the value of the adminURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminURL() {
        return adminURL;
    }

    /**
     * Sets the value of the adminURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminURL(String value) {
        this.adminURL = value;
    }

    /**
     * Gets the value of the versionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionInfo() {
        return versionInfo;
    }

    /**
     * Sets the value of the versionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionInfo(String value) {
        this.versionInfo = value;
    }

    /**
     * Gets the value of the versionList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionList() {
        return versionList;
    }

    /**
     * Sets the value of the versionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionList(String value) {
        this.versionList = value;
    }

}
